[package]
name = "unic-ucd-ident"
version = "0.7.0"
authors = ["The UNIC Project Developers"]
repository = "https://github.com/behnam/rust-unic/"
license = "MIT/Apache-2.0"
description = "UNIC - Unicode Character Database - Identifier Properties"
keywords = ["text", "unicode", "character-property"]
categories = ["text-processing", "parsing"]

exclude = [
    "tests/lexical_class_tests",
]

[features]
default = [ "xid" ]
pattern = []
xid = []
id = []

[dependencies]
unic-char-property = { path = "../../char/property/", version = "0.7.0" }
unic-char-range = { path = "../../char/range", version = "0.7.0" }
unic-ucd-version = { path = "../version/", version = "0.7.0" }

[dev-dependencies]
unic-ucd-category = { path = "../category/", version = "0.7.0" }
regex = "0.2"
matches = "0.1"

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "behnam/rust-unic" }
is-it-maintained-open-issues = { repository = "behnam/rust-unic" }
appveyor = { repository = "behnam/rust-unic", branch = "master", service = "github" }
travis-ci = { repository = "behnam/rust-unic", branch = "master" }
