[package]
name = "unic-gen"
version = "0.0.0"
edition = "2018"
authors = ["The UNIC Project Developers"]
repository = "https://github.com/open-i18n/rust-unic/"
license = "MIT/Apache-2.0"
description = "UNIC â€” Table Generation"
publish = false

[dependencies]
unic-char-range = { path = "../unic/char/range/", version = "0.9.0" }

# Command line argument parsing
clap = "2.29"

# Memoization
lazy_static = "1.0"

# Parsing
itertools = "0.7"
matches = "0.1"
regex = "0.2"
